<?php
$currentProduct = $block->getCurrentProduct();

if($currentProduct->getCategoryIds()){
  foreach($currentProduct->getCategoryIds() as $catIDs){
    $catID = $catIDs;
  }
} else{
  $catID = 3;
}

?>

<a href="" id="notify_product_url" class="notify_product_url">  
<div id="contentNotification" class="contentNotification <?=$block->getPosition()?>" style="display:none">

<img id="notifiy_product_img" class="notifiy_product_img" src="">
   <div style="vertical-align:middle;">
      <span class="notify_product_message">Our customer purchased a</span><br>
      <span class="notify_product_name" id="notify_product_name"></span><br>
      <span class="purchase_ago"></span>
  </div> 
</div>
</a>
<script>
  window.getHowLong = <?=$block->getHowLong(); ?>;
  window.salesnotification_enable = <?=$block->getStatus(); ?>;
  window.salesnotification_current_catID = <?=$catID; ?>;
</script>
